/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReactFooRouteImport } from './routes/react-foo'
import { Route as ReactBarRouteImport } from './routes/react-bar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReactFooSplatRouteImport } from './routes/react-foo/$'
import { Route as ReactBarSplatRouteImport } from './routes/react-bar/$'

const ReactFooRoute = ReactFooRouteImport.update({
  id: '/react-foo',
  path: '/react-foo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactBarRoute = ReactBarRouteImport.update({
  id: '/react-bar',
  path: '/react-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactFooSplatRoute = ReactFooSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ReactFooRoute,
} as any)
const ReactBarSplatRoute = ReactBarSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ReactBarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/react-bar': typeof ReactBarRouteWithChildren
  '/react-foo': typeof ReactFooRouteWithChildren
  '/react-bar/$': typeof ReactBarSplatRoute
  '/react-foo/$': typeof ReactFooSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/react-bar': typeof ReactBarRouteWithChildren
  '/react-foo': typeof ReactFooRouteWithChildren
  '/react-bar/$': typeof ReactBarSplatRoute
  '/react-foo/$': typeof ReactFooSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/react-bar': typeof ReactBarRouteWithChildren
  '/react-foo': typeof ReactFooRouteWithChildren
  '/react-bar/$': typeof ReactBarSplatRoute
  '/react-foo/$': typeof ReactFooSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/react-bar' | '/react-foo' | '/react-bar/$' | '/react-foo/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/react-bar' | '/react-foo' | '/react-bar/$' | '/react-foo/$'
  id:
    | '__root__'
    | '/'
    | '/react-bar'
    | '/react-foo'
    | '/react-bar/$'
    | '/react-foo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReactBarRoute: typeof ReactBarRouteWithChildren
  ReactFooRoute: typeof ReactFooRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/react-foo': {
      id: '/react-foo'
      path: '/react-foo'
      fullPath: '/react-foo'
      preLoaderRoute: typeof ReactFooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-bar': {
      id: '/react-bar'
      path: '/react-bar'
      fullPath: '/react-bar'
      preLoaderRoute: typeof ReactBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-foo/$': {
      id: '/react-foo/$'
      path: '/$'
      fullPath: '/react-foo/$'
      preLoaderRoute: typeof ReactFooSplatRouteImport
      parentRoute: typeof ReactFooRoute
    }
    '/react-bar/$': {
      id: '/react-bar/$'
      path: '/$'
      fullPath: '/react-bar/$'
      preLoaderRoute: typeof ReactBarSplatRouteImport
      parentRoute: typeof ReactBarRoute
    }
  }
}

interface ReactBarRouteChildren {
  ReactBarSplatRoute: typeof ReactBarSplatRoute
}

const ReactBarRouteChildren: ReactBarRouteChildren = {
  ReactBarSplatRoute: ReactBarSplatRoute,
}

const ReactBarRouteWithChildren = ReactBarRoute._addFileChildren(
  ReactBarRouteChildren,
)

interface ReactFooRouteChildren {
  ReactFooSplatRoute: typeof ReactFooSplatRoute
}

const ReactFooRouteChildren: ReactFooRouteChildren = {
  ReactFooSplatRoute: ReactFooSplatRoute,
}

const ReactFooRouteWithChildren = ReactFooRoute._addFileChildren(
  ReactFooRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReactBarRoute: ReactBarRouteWithChildren,
  ReactFooRoute: ReactFooRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
